---
# GitHub Actions multi-job workflow for Windows to:
# - build using matrix of Visual C++ versions
# - build using latest defaults and run tests against number of databases
name: "CI Windows"

on:
  push:
    branches:
    - main
    - ml/*
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/ci-linux.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/ci-linux.yml'

jobs:
  test-mariadb:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        mariadb: ['10.10', '10.3']
    steps:
      - uses: actions/checkout@v3
      - name: Install MariaDB
        uses: ankane/setup-mariadb@v1
        with:
          database: nanodbc
          mariadb-version: ${{ matrix.mariadb }}
      - name: Install MySQL ODBC Driver 5.3
        run: |
          choco install mysql-odbc
      - name: Check
        run: |
          mysql -D nanodbc -e 'SELECT VERSION()'
          Get-OdbcDriver -Platform 64-bit | Select-Object -ExpandProperty Name
      - name: Configure
        run: |
          cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build --config Release --target mysql_tests
      - name: Test
        run: |
          $env:NANODBC_TEST_CONNSTR_MYSQL="Driver={MySQL ODBC 5.3 ANSI Driver};Server=127.0.0.1;Database=nanodbc;User=root;Password=;big_packets=1;"
          ctest --test-dir ${{ github.workspace }}/build --build-config Release --output-on-failure --no-tests=error -R mysql_tests
